name: CI-dummy

on: 
  pull_request:
    branches:
      - main
    path-ignore: 
      - 'src/**'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run:  echo "No Test Needed..."